updated song files and generated pdfs

diff --git a/refresh_songlist b/refresh_songlist
--- a/refresh_songlist
+++ b/refresh_songlist
@@ -1,11 +1,13 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 # variables
 SONGLIST="allsongs.txt"
 VERSION="v.$(date +'%F')"
 
-# if SONGLIST exists, empty the file. fail if not found.
-test -f "$SONGLIST" && >"$SONGLIST" || { echo "Could not find $SONGLIST!" >&2; exit 1; }
+test -f "$SONGLIST" || { echo "Could not find $SONGLIST!" >&2; exit 1; }
+
+# clear the existing file
+truncate -s 0 "$SONGLIST"
 
 # file header
 cat << EOF > "$SONGLIST"
@@ -14,8 +16,7 @@ ALL SONGS - ${VERSION}
 EOF
 
 # print the first line of each file to the SONGLIST
-for i in songs/*.txt; do
+for i in songs/*.md; do
     TITLE=$( awk NR==1 "$i" |sed 's/#[[:space:]]//' )
     printf "%s\n" "$TITLE" | sort >> "$SONGLIST"
 done
-
